dist: trusty
sudo: required

language: node_js
node_js:
  - "12.18.3"

addons:
  chrome: stable

before_install:
  - google-chrome-stable --disable-gpu --remote-debugging-port=9222 http://localhost &

branches:
  only:
    - master

env:
  - EMBER_VERSION=dev

jobs:
  fast_finish: true
  allow_failures:
    - env: EMBER_VERSION=dev

install:
  - npm install

script:
  # - npm run test
  - ng build --prod --aot --deploy-url ./ --base-href ./
  - cd dist/poc-estudos-angular-gitpod
  - cp index.html 404.html

notifications:
  email:
    on_failure: change
    on_success: change

# before_install:
#   - export DISPLAY=:99.0
#   - sh -e /etc/init.d/xvfb start

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/poc-estudos-angular-gitpod
  on:
    branch: master
