dist: trusty
sudo: required
language: node_js
node_js:
  - "12.18.3"

addons:
  chrome: stable
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

branches:
  only:
    - master

env:
  - EMBER_VERSION=dev

jobs:
  allow_failures:
    - env: EMBER_VERSION=dev

install:
  - npm install

script:
  - npm run test
  - ng build --prod --aot --deploy-url ./ --base-href ./
  - cd dist/poc-estudos-angular-gitpod
  - cp index.html 404.html

before_install:
  - npm install -g @angular/cli
  - npm install -global firebase-tools
  - export CHROME_BIN=usr/bin/google-chrome
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/poc-estudos-angular-gitpod
  on:
    branch: master
